# Running by command:
# docker-compose up -d

# Remove
# docker-compose down --volumes

# connect throw browser
# http://localhost:8888/



name: jiraRush
services:
#  app:
#    container_name: jiraRush
  db-prod:
    image: postgres
    container_name: postgres-db
    restart: always
    env_file:
      - .env
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_DB=${POSTGRES_DB_DEV}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_DEV_PORT}:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  db-test:
    image: postgres
    restart: always
    container_name: postgres-db-test
    env_file:
      - .env
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_DB=${POSTGRES_DB_TEST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./pgdata-test:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_TEST_PORT}:5432


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    env_file:
      - .env
    restart: always
    ports:
      - ${PGADMIN_PORT}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db-prod
      - db-test
