# Running services:
#   docker-compose up -d

# Remove containers:
#   docker-compose down --volumes



volumes:
  pgdata:
    name: pgdata

name: jiraRush

services:
  jira:
    image: jira-app
    container_name: jira
    ports:
      - "8080:8080"
    build:
      context: .
#      dockerfile: Dockerfile-local-build
      dockerfile: Dockerfile
    depends_on:
      - db-prod
      - nginx
    env_file:
      - config/jira-app-prod.env

  nginx:
    container_name: nginx
    image: nginx:1.13
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/nginx.conf

  db-prod:
    image: postgres:17
    container_name: db-prod
    env_file:
      - config/postgresql-prod.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U jira -d jira" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: unless-stopped