DROP DATABASE IF EXISTS "jira-test";
CREATE DATABASE "jira-test";

-- REVOKE ALL ON DATABASE "jira-test" FROM jira;
-- REVOKE ALL PRIVILEGES ON DATABASE "jira-test" FROM jira;
-- REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM jira;
-- REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM jira;
-- REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public FROM jira;

--REASSIGN OWNED BY jira TO postgres;
--DROP OWNED BY jira;

DROP ROLE IF EXISTS jira;
CREATE ROLE jira LOGIN PASSWORD 'JiraRush';
-- CREATE USER jira WITH ENCRYPTED PASSWORD 'JiraRush';

GRANT ALL PRIVILEGES ON DATABASE "jira-test" TO jira;