DROP DATABASE IF EXISTS jira;
CREATE DATABASE jira;

-- REVOKE ALL ON DATABASE jira FROM jira;
-- REVOKE ALL PRIVILEGES ON DATABASE jira FROM jira;
-- REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM jira;
-- REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM jira;
-- REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public FROM jira;

DROP OWNED BY jira;

DROP ROLE IF EXISTS jira;
CREATE ROLE jira LOGIN PASSWORD 'JiraRush';
-- CREATE USER jira WITH ENCRYPTED PASSWORD 'JiraRush';

GRANT ALL PRIVILEGES ON DATABASE jira TO jira;